### ISSUE TITLE
Conflicting css in articles after introducing tailwindcss

### ISSUE THREAD

**Issue by Erdragh** [Willibald-Gluck-Gymnasium/wgg-homepage#12]
This issue stems from the articles not yet entirely being adjusted to tailwind's syntax and structure, leading to conflicting css rules, which produce some minor visual glitches

**Comment by alexanderhorner** [comment]
Always use scoped css if possible. What conflicts exactly? I haven't observed or at least noticed them.

**Comment by Erdragh** [comment]
https://user-images.githubusercontent.com/29674493/158035674-f6a021f2-eb8b-4e0d-a2ec-5b93c49342e3.mov

Specifically the Issue is with the WGG Icon in the Header, there was also an issue in the ArticleContent, but that was fixed.

**Comment by alexanderhorner** [comment]
Haha interesting 

I will take a look
