### ISSUE TITLE
Extreme visual glitch due to inertiajs and forms

### ISSUE THREAD

**Issue by Erdragh** [Willibald-Gluck-Gymnasium/wgg-homepage#13]
This issue concerns the SearchBar in the primary header. The problem with it is that when pressing enter or the submit button on what is essentially just a form, the site doesn't make an inertia request but rather a complete reload. When this page loads and you click on a link that leads to the home page, there will be positioning glitches, assumed to stem from the css not being loaded correctly. This is a usability hindering bug and therefore should be high priority.

**Comment by alexanderhorner** [comment]
Vielleicht hilft das https://inertiajs.com/manual-visits

**Comment by alexanderhorner** [comment]
Fixed in #34
