### ISSUE TITLE
Terminanzeige/Kalender

### ISSUE THREAD

**Issue by Lelidle** [Willibald-Gluck-Gymnasium/wgg-homepage#130]
Auf der Startseite muss ein Kalender oder eine andere Art der Terminanzeige sichtbar sein. 
Herr Schiffer muss ggf. über einen passwortgeschützten Zugang Termine eintragen können

**Comment by alexanderhorner** [comment]
<img width="100%" alt="Bildschirm­foto 2023-01-31 um 14 28 13" src="https://user-images.githubusercontent.com/18349361/215773288-ce1a3281-9675-4259-8cc6-472dc4f89d59.png">
