### ISSUE TITLE
Einzelartikel bei tags

### ISSUE THREAD

**Issue by Lelidle** [Willibald-Gluck-Gymnasium/wgg-homepage#178]
Wenn bei Anzeige eines tags nur ein Artikel erscheinen würde, wäre es vermutlich sinnvoller, wenn direkt der Artikel angezeigt würde?

Ähnlich für Suchfunktion, aber da kommt das vermutlich quasi nie vor.

**Comment by alexanderhorner** [comment]
Wieso sollte ein Tag nur einen Artikel haben?

**Comment by Lelidle** [comment]
Aktuell ist das z.B. bei Downloads der Fall - sollte natürlich nicht so sein, aber als Fallback nützlich, wenn jemand einen neuen Tag baut und bisher sonst noch nichts da ist, der tag aber verwendet wird.

**Comment by alexanderhorner** [comment]
Das weicht halt von dem Verhalten ab, das ich als Nutzer erwarten würde, wenn ich auf einen Tag/ Link gehe. Würde mich vielleicht wundern, wieso ich zu näm Artikel komme, anstatt zu der Übersicht aller Artikel mit dem Tag, auch wenn's nur einen gibt. Wenn ich dann auf den Tag im Artikel klicke, komm ich wieder zurück zu dem Artikel. Wirkt auch wie ein Bug dann.
