### ISSUE TITLE
Archivierung

### ISSUE THREAD

**Issue by Lelidle** [Willibald-Gluck-Gymnasium/wgg-homepage#199]
Skript, das ausgelaufene Artikel in einen Ordner schiebt?

Funktioniert lokal nicht?

**Comment by alexanderhorner** [comment]
Das Archiv funktioniert so, dass einfach die Artikel nach der expireOn property gefiltert werden. (expireOn =< Date.now() oder so)

Der Pfad bleibt also gleich. Ist das eine gewünschte Funktionalität?
