### ISSUE TITLE
Text overflow in hero section

### ISSUE THREAD

**Issue by lbirkert** [Willibald-Gluck-Gymnasium/wgg-homepage#214]
![Screenshot_20230314-210135_DuckDuckGo](https://user-images.githubusercontent.com/88548934/225123155-2965c5a0-53e6-4c9b-ab11-d2a81eb3d909.png)

**Comment by alexanderhorner** [comment]
Danke, muss das mal überarbeiten.

**Comment by alexanderhorner** [comment]
Sollte gefixed sein?

**Comment by lbirkert** [comment]
yep
