### ISSUE TITLE
New search functionality does not display

### ISSUE THREAD

**Issue by Erdragh** [Willibald-Gluck-Gymnasium/wgg-homepage#49]
## Problem
The SearchBar in the MainHeader and on the /results page do not appear. In the inspector they are just comments, with v-if in them:
![image](https://user-images.githubusercontent.com/29674493/167480857-39b48471-d40d-4639-9c65-ab8a57535a82.png)
![image](https://user-images.githubusercontent.com/29674493/167480751-64953282-e6d8-406d-b50b-09509f41b257.png)

## Steps to reproduce:
- clone this repository
- do the necessary setup as described in `CONTRIBUTING.md`
- start the server with `php artisan serve`
- open `localhost:8000` in a browser

**Comment by Erdragh** [comment]
## Console output:
![image](https://user-images.githubusercontent.com/29674493/168008106-cc435eb5-2cc7-4d91-88d2-126c7b57630c.png)

**Comment by alexanderhorner** [comment]
.env anpassen

```shell
# Scout Search
MIX_SCOUT_PREFIX=jan_local_
MIX_ALGOLIA_APP_ID=2XC7702REX
```
