### ISSUE TITLE
Frage zu Javascript-Fragebogen

### ISSUE THREAD

**Issue by Scriptor25** [Willibald-Gluck-Gymnasium/wgg-homepage#60]
Wie kann ich diesen Fragebogen einbauen:
https://www.wgg-neumarkt.de/seiten/text/unterricht/physik/19_psem_e_mobil/
Der besteht halt komplett aus Javascript.

**Comment by Erdragh** [comment]
Als Antwort zur Frage:
Dreckig, aber schnell. Ich bin mir auch nicht 100% sicher ob es funktionieren würde:
1. Alle *.js Dateien werden ja mit dem `<script>` tag eingefügt. Ich würd sagen, nimm den Inhalt der Dateien und pack den mit in den javascript teil der index.html
2. Mach dann einen iFrame im Artikel, der ne id hat, also: `<iframe id="fragebogen">`
3. Mach ein script element, wo du, wie hier: https://stackoverflow.com/questions/16504816/how-to-set-html-content-into-an-iframe, den Inhalt der alten index.html in den iframe packst

Also irgendwie sowas:
```html
---
...
---
<iframe id="fragebogen"/>
<script type="text/javascript">
var iframe = document.getElementById("fragebogen");
iframe.contentWindow.document.write("<html><body>Hello world</body></html>");
</script>
```
Wobei halt anstelle von `<html><body>Hello world</body></html>` der Inhalt von der index.html ist.

---

Wenn man's tatsächlich schön integrieren wollen würde, würde das viel mehr Arbeit bedeuten, wo ich mir nicht sicher bin ob _du_ das könntest. Es würde theoretisch mit custom components et cetera gehen, aber das wär ein enormer Aufwand.

Wenn das oben beschriebene nicht funktioniert, müsste man wohl einen anderen Weg gehen, also update dieses Issue dann bitte dementsprechend, wenn's nicht funktioniert.
