### ISSUE TITLE
Error with 'Run Dusk Test'

### ISSUE THREAD

**Issue by ScriptorGames** [Willibald-Gluck-Gymnasium/wgg-homepage#84]

**Comment by ScriptorGames** [comment]
![Physik   Schulhaus · Willibald-Gluck-Gymnasium_wgg-homepage@18a3d99 - Google Chrome 24 06 2022 14_21_11](https://user-images.githubusercontent.com/83061405/175534194-e5603580-8840-4fbe-97c0-be7c41a38d4b.png)

**Comment by alexanderhorner** [comment]
Der Artikel physik_grav hat einen syntax Fehler. 

PS: änder bitte den Namen/Link dieses Artikels. Abkürzungen wie „grav“ sind verwirrend. Und - ist in links auch besser lesbar als _.
